### ISSUE TITLE
The lab idea.

### ISSUE THREAD

**Issue by ArsStels** [raiguard/EditorExtensions#101]
Your mod I use exclusively for labs, as it is very cool in that respect.
Could you do the same as the Sandbox? That is, so that the game can not go into cheat mode without turning on this option in the startup settings. And have access only to the lab. (Especially, in the player options, everyone can do with the main map whatever he wants)

**Comment by raiguard** [comment]
The nature of the map editor is that it is all-powerful. Even if I wanted to, I cannot restrict what you can do in the editor. You can delete entire surface, change forces, replace all trees with biter nests, or whatever you want, and I can't stop you. If you want multiplayer-friendly sandboxes, check out the [Blueprint Sandboxes](https://mods.factorio.com/mod/blueprint-sandboxes) mod.

You can prevent players from using the map editor in multiplayer by using the `/permissions` menu and disabling the `toggle map editor` permission. But once they are in the editor, you're out of luck.
