### ISSUE TITLE
Biters in Personal Lab with RSO enabled

### ISSUE THREAD

**Issue by pla** [raiguard/EditorExtensions#103]
### Description

I could narrow the the biters in lab problem down to RSO. Attached is a simple brand new save with only EE and RSO installed. Factorio version is 1.1.76

### Reproduction

It is straight forward to reproduce:
1. have RSO installed
2. enable personal lab
3. open lab
4. biters and ores are there

I did no further testing with any settings
[EE_RSO test.zip](https://github.com/raiguard/EditorExtensions/files/10950564/EE_RSO.test.zip)

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/224581310-f1dff179-cc6f-4782-8cb6-24d97d3ae72a.png)
Honestly, I'm going to call this a bug in RSO. It should respect the fact that enemy bases are disabled on the surface.

**Comment by mkaito** [comment]
RSO author says there's a remote interface you can use to set a surface as ignored: https://mods.factorio.com/mod/rso-mod/discussion/640edd1cb1818dc70225f428
