### ISSUE TITLE
Suggestion: Allow usage of legacy/old-style loaders

### ISSUE THREAD

**Issue by USSX-Hares** [raiguard/EditorExtensions#105]
### Description

Legacy infinity loaders yet had perfomance issue also had a killer-feature benefit of being able to load different sides of belt with different item. This had a great usage for small testing purposes. So, the question -- can you add them back with a performance note like on inifinity chests?

**Comment by raiguard** [comment]
Sorry, but the old loaders will not be coming back. They were very difficult to maintain, had issues saturating high-speed belts, and were really janky overall. They weren't removed purely for the UPS improvement, they also had unfixable issues.
