### ISSUE TITLE
Can not configure infinity pipe

### ISSUE THREAD

**Issue by anakreontas** [raiguard/EditorExtensions#108]
In the infinity pipe GUI:
1. All radio buttons can be enabled (see screenshot)
2. The configuration window doesn't close neither with the keyboard not with the mouse.
3. To close the window I tried to delete the pipe. This crashes the game.

I am using the latest version on 14/03/2023.

![Screenshot 2023-03-14 215551](https://user-images.githubusercontent.com/9968434/225149299-6cf517a2-c340-46cf-ad4a-4f8cbd0d20fe.png)
 
`The mod Editor Extensions (2.0.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event EditorExtensions::on_nth_tick(1)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__index'
	__EditorExtensions__/scripts/infinity-pipe.lua:152: in function 'update_fluid_content_bar'
	__EditorExtensions__/scripts/infinity-pipe.lua:716: in function 'handler'
	__core__/lualib/event_handler.lua:56: in function <__core__/lualib/event_handler.lua:54>`

**Comment by anakreontas** [comment]
I have attached an empty game with an infinity pipe.
[infinity_pipe.zip](https://github.com/raiguard/EditorExtensions/files/10974333/infinity_pipe.zip)

**Comment by raiguard** [comment]
Your version of `flib` is out of date - please update it to 0.12.5. I will leave this open as a reminder to fix the dependency version.
