### ISSUE TITLE
UI does not reset in possible edge case

### ISSUE THREAD

**Issue by ColbyHepworth** [raiguard/EditorExtensions#109]
### Description

 UI does not reset to the left. You can recreate with the Blueprint sandboxes mod when you go into the sandbox mode (Shift + b) then enter editor mode, then exit sandbox mode (Shift + b) without exiting the editor
![image](https://user-images.githubusercontent.com/13155994/225943013-0b7c305e-bae5-42f4-a1f0-34c117758eff.png)

**Comment by raiguard** [comment]
Thanks for the report. These two mods aren't really designed to be used together, as the map editor lets you easily circumvent the "sandbox" nature of blueprint sandboxes. I would recommend using the built-in testing lab in EE instead, which achieves a similar effect, but isn't as restricted.

I tried to work around this, but there is no catch-all event for when a player's controller changes, and there never will be.
