### ISSUE TITLE
Crash: Entity invalid 

### ISSUE THREAD

**Issue by BinkanSalaryman** [raiguard/EditorExtensions#110]
### Description

The mod Editor Extensions (2.0.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event EditorExtensions::on_nth_tick(15)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__index'
	__EditorExtensions__/scripts/infinity-loader.lua:46: in function 'sync_chest_filter'
	__EditorExtensions__/scripts/infinity-loader.lua:177: in function 'handler'
	__core__/lualib/event_handler.lua:56: in function <__core__/lualib/event_handler.lua:54>

### Reproduction

Idk, I just mined an infinity loader in the EE/Testing scenario

**Comment by raiguard** [comment]
Was fixed in 4c22346, I accidentally put the wrong issue number in the commit. :/
