### ISSUE TITLE
Problems migrating save game from 1.13 to 2.0

### ISSUE THREAD

**Issue by chindraba-work** [raiguard/EditorExtensions#115]
### Description

The mod EditorExtentions 2.0.6 (and as far back as 2.0.0) has a missing file which prevents me from loading a map save made with EditorExtentions 1.13.7. I'm sure it has something to do with the version bump to 2, and that removing something from the save will fix it, just not sure what. I deleted all the infinity pipes and chests (I think) without success.

I'm willing to delete the offending item, if I know what it is, and where it is.

[factorio-current.log](https://github.com/raiguard/EditorExtensions/files/11073515/factorio-current.log)
[Save file](https://drive.google.com/file/d/1llnKiqCl05N7hrxtlLcbeCtdlUH6t3pS/view?usp=share_link)

### Reproduction

To reproduce launch the game and attempt to open the saved file. All other mods are off (except flib). And version of EE prior to 2.0.0 will load the game, any version 2.0.0 or higher will not.

**Comment by raiguard** [comment]
That save file actually has 1.13.0. You'll need to load it with 1.13.7, then save it and load it with 2.0.x, for it to work.

**Comment by raiguard** [comment]
Ah, I see what's going on. You somehow saved this game as a new scenario, so even though it has the EE testing scenario code, it isn't being updated correctly on 1.13.7.

I manually removed the `control.lua` file from your save, which will fix the issue. Scenarios in general are really janky to work with and can have problems like this. I recommend always just saving your games normally.

[__Railyard Design Fixed.zip](https://github.com/raiguard/EditorExtensions/files/11083866/__Railyard.Design.Fixed.zip)
