### ISSUE TITLE
Character appears on the wrong surface after exiting the testing lab

### ISSUE THREAD

**Issue by bo-rys** [raiguard/EditorExtensions#116]
### Description

When combined with the Space Exploration mod, if the spaceship that your character is currently on automatically docks while you are in the testing lab, it looks like you won't correctly respawn on the new surface where the spaceship got anchored when you exit the testing lab

### Reproduction

1. Fly on a spaceship
2. Switch into the testing lab
3. The spaceship automatically docks
4. Exit the testing lab
5. Reappear in empty space on the surface of another flying spaceship, or even get stranded in the testing lab

**Comment by raiguard** [comment]
I am unable to detect when a spaceship lands, so I have disallowed toggling the map editor while riding on a spaceship.

**Comment by bo-rys** [comment]
Thanks for looking at the issue. But from what I've seen, a major use case of this mod is to work on something in the testing lab while waiting for the spaceship to arrive, and this change would disallow that. I personally would rather get stuck in space that not be able to do that.
