### ISSUE TITLE
Invalid location, must be placed on a surface belonging to a zone

### ISSUE THREAD

**Issue by diilmac** [raiguard/EditorExtensions#121]
### Description

When Im trying to place Cargo rocket silo or Cargo landing Pad.

Both items comes from Space Exploration mod

![image](https://user-images.githubusercontent.com/10393681/229311422-64692cbb-e449-4e0f-9bb1-1e7de81a8db6.png)

**Comment by raiguard** [comment]
SE has some weird restrictions on placing these entities. Based on what I've seen from blueprint sandboxes, even if I figure out how to make them place-able, it will still complain about the force. I don't think it's worth it.
