### ISSUE TITLE
Testing lab and Companion Drones

### ISSUE THREAD

**Issue by kryojenik** [raiguard/EditorExtensions#126]
### Description

Editor Extensions and Companion Drones mods and the testing lab setting of Editor Extensions enabled.

When entering a testing lab surface the companion drones think your buldings, and base worker robots are enemys and start attacking.  A bit after you return they stop attacking.

Toggling off your Companion Drone attack before entering the testing lab prevents this from happening.
[EE - Companion - force.zip](https://github.com/raiguard/EditorExtensions/files/11183769/EE.-.Companion.-.force.zip)

### Reproduction

1. Load the attached save file.
2. Make sure the Editior Extension Per Player setting of testing lab is set to Force or Player
3. Enter the testing lab
4. Wait a few seconds
5. Exit the testing lab to find your companion drones running amok.

**Comment by raiguard** [comment]
There isn't anything I can do on EE's side. IMO companion drones should be removed when you enter the editor, and restored when you exit, like actual robots do. You'll have to reach out to Klonan to fix this.
