### ISSUE TITLE
Can't load old savegames with 1.13.7 or older

### ISSUE THREAD

**Issue by warbaque** [raiguard/EditorExtensions#127]
### Description

Loading old savegame with EditorExtensions 2.x.x fails

```
...Data/Roaming/Factorio/temp/currently-playing/control.lua:5: module __EditorExtensions__.scripts.scenarios.testing not found;  no such file __EditorExtensions__/scripts/scenarios/testing.lua
stack traceback:
	[C]: in function 'require'
	...Data/Roaming/Factorio/temp/currently-playing/control.lua:5: in main chunk
```

Is it somehow possible to convert my 1.x.x test worlds to v2, or I'm I stuck with old version?

### Reproduction

1. save game with v1
2. load game with v2

`This is a BREAKING UPDATE. Your existing testing setups will no longer function as they once did`

Doesn't imply that savegames doesn't load at all. Which is a bit problematic for me since I have 28 different planning worlds with all my blueprint skeletons.

**Comment by raiguard** [comment]
1.13.7 was supposed to convert your testing scenarios to fix this issue. However, it appears that that did not work all the time.

I've re-added the missing file and put code in it to force-reload the scenario script, which should fix this issue.

**Comment by warbaque** [comment]
Well, there's also many save files with <= 1.13.7, some with 1.12.x

So there's also many savefiles that have never seen version 1.13.7 :)

Should I now try to load and re-save all files with v2 just in case the migration functionality is obsoleted in the future?

**Comment by raiguard** [comment]
Yeah, you should be able to load any of them with V2 now
