### ISSUE TITLE
Construction robots in-flight in the main surface teleport with the player to the lab the first time

### ISSUE THREAD

**Issue by timeshifter** [raiguard/EditorExtensions#128]
### Description

..and then are stuck there. Only seems to happen the first time the lab is visited. Inventory sync is disabled.

### Reproduction

Start new game, have construction robots either by quick start mod or console, have them build something, switch to the lab while they're in flight. The bots will teleport to the lab surface and disappear from the main surface entirely.

**Comment by timeshifter** [comment]
Correction, it just happened again after already having visited the lab, and it was *all* of my bots, not just the ones in flight. This is a problem because I don't have robots unlocked yet, I used a quick start mod to start with them, and have to keep using console to re-add them.

**Comment by raiguard** [comment]
Are you on the newest version? I thought I specifically fixed this in 2.0.0.

**Comment by timeshifter** [comment]
I thought I was, but apparently I was waaay behind. My bad.

**Comment by raiguard** [comment]
Does updating fix the problem?

**Comment by timeshifter** [comment]
Yep, looks like it, the two surfaces have their own bots now. Thanks.

**Comment by raiguard** [comment]
Thanks for using the mod!

**Comment by timeshifter** [comment]
Thank you for making it, I get so much utility out of it. So very helpful.
