### ISSUE TITLE
[EE 2.1.1] Remove Fluids Infinity Pipe UI Resets

### ISSUE THREAD

**Issue by adugaue** [raiguard/EditorExtensions#129]
### Description

Hello, Flood here again.

It looks like Editor Extensions has an issue saving the UI when you've selected to remove fluids at a specific unit or % count. I recorded a video this time. 

Let me know if you need anything else.

### Reproduction

Here's a video of my reproducing it: https://youtu.be/WvZhFNWvHnE 

Place a pipe to remove units from a fluid tank.
Click on Remove radial
Change "%" to "u"
Type "35" in units field
Click anyone on the UI to de-select units field. 
Close UI.
Reopen the pipe and see everything on the UI is reset.

**Comment by raiguard** [comment]
This is happening because there isn't any infinity pipe filter actually set. If you do this in the base game infinity pipe, it does the same thing. I can't set an infinity pipe filter unless you select a fluid.
