### ISSUE TITLE
Super pump temperature is wired up to pump speed

### ISSUE THREAD

**Issue by whiterook6** [raiguard/EditorExtensions#130]
### Description

When using a Super pump, I noticed the temperature of the fluid in the display is wired up to the configured flow rate. I don't think it affects the actual fluid temperature.

Screenshots:
<img width="603" alt="Screenshot 2023-04-18 at 1 05 17 PM" src="https://user-images.githubusercontent.com/5151965/232893719-aa994458-e1f3-4578-bcc8-755ffe760348.png">
<img width="585" alt="Screenshot 2023-04-18 at 1 05 04 PM" src="https://user-images.githubusercontent.com/5151965/232893731-8edfaedc-43b8-4687-9ced-b2c770610c81.png">

The fluid isn't actually affected by the pump's setting:
<img width="785" alt="Screenshot 2023-04-18 at 1 11 34 PM" src="https://user-images.githubusercontent.com/5151965/232894043-e3cf6cb7-198e-44d4-b9a9-6a45b5beebbe.png">
<img width="758" alt="Screenshot 2023-04-18 at 1 11 29 PM" src="https://user-images.githubusercontent.com/5151965/232894055-c9664c4e-d742-4fbe-8bb7-204f92cec8a3.png">

Also there's something going on with the red X and the 99G in the dialog, don't know what that's about.

### Reproduction

1. Place a Super pump
2. Attach an infinity pipe with water created at "At least 100" with regular 15C water.
3. Observe the temperature in the Super pump dialog change as you play with the speed slider

**Comment by raiguard** [comment]
What you're looking at is the internal mechanics of the pump. The temperature of the "speedfluid" is how I change the speed of the pump. Before 2.0, the pump had a fully custom GUI, but this didn't allow you to connect it to the circuit network. So instead, in 2.0, I attach the speed slider below the default GUI, which allows you to change circuit settings, but unfortunately also shows the speedfluid.

Aka, this isn't a bug, but I understand why it's confusing.
