### ISSUE TITLE
Feature Request: Allow filling surface with lab tile pattern

### ISSUE THREAD

**Issue by USSX-Hares** [raiguard/EditorExtensions#131]
### Description

By now, editor extensions allow to use lab tile 1 and lib tile 2, but there is no option to fill the selected area with the alternating color pattern.

**Comment by raiguard** [comment]
![image](https://github.com/raiguard/EditorExtensions/assets/3515394/ee9a9847-43ab-49d7-8431-df63bbd7aefc)
You can fill a whole surface with lab tiles in the editor. Are you asking for a selection tool instead?

**Comment by USSX-Hares** [comment]
> ![image](https://user-images.githubusercontent.com/3515394/243192742-ee9a9847-43ab-49d7-8431-df63bbd7aefc.png) You can fill a whole surface with lab tiles in the editor. Are you asking for a selection tool instead?

Well, yes, I was asking for a selection tool.
Have found a workaround with the selection tool script execution:

```lua
local tiles = { }
local tile_types = { [0] = "lab-dark-1", [1] = "lab-dark-2" }

game.player.print(string.format("Replacing tiles on region from (%i, %i) to (%i, %i)...", area.left_top[1], area.left_top[2], area.right_bottom[1], area.right_bottom[2]))

for x = area.left_top[1], area.right_bottom[1] - 1
do
    for y = area.left_top[2], area.right_bottom[2] - 1
    do table.insert(tiles, { position={ x, y }, name=tile_types[(x+y) % 2] })
    end
end

game.player.surface.set_tiles(tiles, false)
```
