### ISSUE TITLE
Exotic industries: Pipe provides low temperature steam

### ISSUE THREAD

**Issue by anakreontas** [raiguard/EditorExtensions#132]
### Description

Two issues with this mode:

1. In the saved game there are two assemblers, one takes steam from a boiler (works) the other from a pipe. The second doesn't work, I think the steam temperature is not right.
2. There should be a recipe for making pipes. I can see pipes as a required ingredient for other recipes but I can't make them. Deconstruction plan does not distinguish between a pipe and insulated pipe (different recipe).  
[steam_temperature.zip](https://github.com/raiguard/EditorExtensions/files/11368324/steam_temperature.zip)

### Reproduction

Load save file
 1. The assembler on the left doesn't work.
 2. Try to make a pipe

**Comment by raiguard** [comment]
Yeah, you have to set the temperature in the infinity pipe GUI. The infinity pipe doesn't care what the machine wants, it defaults the temperature to the minimum temperature for the fluid prototype. For some reason, steam's minimum is 15 degrees, which makes zero sense, but that's how it was coded.
