### ISSUE TITLE
Puzzle - No sure if it a bug

### ISSUE THREAD

**Issue by francoisdejgr** [raiguard/EditorExtensions#136]
Greetings

This morning I updated all my mods then suddenly I am getting the following error:

Error while running setup for entity prototype "ee-super-pump" (pump): next_upgrade target (5d-pump-02) must have the same collision mask

I then need to disable both this great mod and Squeak Through before Factorio will load.

Any suggestions will be appreciated

**Comment by raiguard** [comment]
This is caused by the menace that is Squeak Through. Please report this to them.
