### ISSUE TITLE
Infinity wagon filter not saved to blueprints

### ISSUE THREAD

**Issue by Tronaek** [raiguard/EditorExtensions#139]
### Description

I am using Editor Extensions 2.1.3 and at some point the wagon filters stopped saving or printing to the world.  I know this was an issue before and has been fixed so this must be an edge case.  I've attached the blueprint that is problematic.
[blueprint.txt](https://github.com/raiguard/EditorExtensions/files/11779246/blueprint.txt)

Also there are remaining elements left on the map view of the wagons after they are deleted.  Almost like something is left behind but cant be selected or deleted.

**Comment by raiguard** [comment]
Could you please attach a save file? I cannot reproduce this.

**Comment by USSX-Hares** [comment]
@raiguard I encountered this issue too.
The wagon loses its infinity filters when the blueprint is updated.

**Comment by raiguard** [comment]
Are you using "select new contents for blueprint"? If so, that is a known issue and there is nothing I can do to fix it. It's a flaw in the modding API.

**Comment by USSX-Hares** [comment]
I guess so.
However, you can help getting more attention to the request I've made recently.

https://forums.factorio.com/viewtopic.php?f=28&t=109220&p=594144#p594144

**Comment by raiguard** [comment]
The API will be much improved in 2.0.

**Comment by USSX-Hares** [comment]
> The API will be much improved in 2.0.

What is the source of this statement?
Was there any non-FFF publications related to this?
