### ISSUE TITLE
Researched tech in lab gets out of sync over time

### ISSUE THREAD

**Issue by mkaito** [raiguard/EditorExtensions#140]
### Description

There's a setting under Map Settings, "match research in test lab". I've noticed that once in a while, the lab won't have some tech I've researched outside of the lab. This happens infrequently, but repeatedly.

Workaround is to disable and then reenable the setting, forcing the research to be reevaluated.

### Reproduction

I have not been able to reliably reproduce it. It happens infrequently, over long periods of time.

**Comment by raiguard** [comment]
Unfortunately there isn't much I can do without a consistent reproduction. Please let me know if you find one.
