### ISSUE TITLE
Entering and Leaving EE lab  ejects you from a spider

### ISSUE THREAD

**Issue by TheRealBurgersNFries** [raiguard/EditorExtensions#144]
### Description

When you enter EE lab while travelling in a spider, exiting the lab drops you off at your last known location, instead of returning you to the spider

### Reproduction

1. Load save file
2. move spidertron with remote
3. enter EE lab
4. Leave EE lab

https://drive.google.com/file/d/1ZSqRyTWD4u_r4YHE18szeuksxnmIgj2E/view?usp=drive_link

**Comment by raiguard** [comment]
EE doesn't do anything special with the map editor toggling, it simply calls `player.toggle_map_editor()`, so this isn't a _bug_ per se. However, I think it's a good feature so I will add it.
