### ISSUE TITLE
Crash when copy-pasting settings in infinity accumulator

### ISSUE THREAD

**Issue by TobTobXX** [raiguard/EditorExtensions#146]
### Description

This is the error that pops up:

```
The mod Editor Extensions (2.2.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event EditorExtensions::on_entity_settings_pasted (ID 33)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__index'
	__EditorExtensions__/scripts/infinity-loader.lua:150: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>
```

Factorio version: 1.1.87
Editor extension version: 2.2.0
flib version: 0.12.9

### Reproduction

1. Open an empty lab world (and delete the preexisting structures)
2. Place two default Infinity Accumulators
3. Switch one to "Buffer" mode.
4. Copy the settings of the buffer acumulator using shift-right click.
5. Paste into the other accumulator using shift-left click.
6. Enjoy the beautiful error pop-up.

**Comment by TobTobXX** [comment]
If you give me a week of time, I'll probably also come up with a PR to fix it. I'd love to try my hand at it, as I'm just getting started in mod dev.

**Comment by raiguard** [comment]
Thanks for the offer, but fortunately this is a pretty simple fix.

**Comment by TobTobXX** [comment]
I tried to find the error, but I just don't get it.

Something very weird is happening, that we land in the event handler for the infinity loader, not the infinity accumulator. Also the error claims that the LuaEntity is invalid, but I just can't see where it was invalidated, considering I copied the settings _after_ I switched it to buffer mode.

Please, go ahead and fix it. But link the commit here, I'm very interested in what was wrong. Anyway, I learned a lot.

**Comment by raiguard** [comment]
This happened because I'm using the [event_handler](https://github.com/wube/factorio-data/blob/master/core/lualib/event_handler.lua) library, which lets you specify multiple handlers to be run for a given event. The entity was invalidated when the handler in `infinity-accumulator.lua` ran, so the handler in `infinity-loader.lua` crashed because I forgot to add the validity check. `event_handler` does not abort when something is invalid because always checking would hurt performance, and it's easy to do on the mod's side.

**Comment by TobTobXX** [comment]
Ah, I see. I somehow assumed event handlers would be registered on an entity/surface/whatever, but events are global and all handlers for `on_settings_pasted` will receive the event.

If I may ask, why are you using `event_handler.add_libraries()` instead of `game.on_event()`? Is there a difference between these two interfaces, or is it just because it makes the code look how you want?

**Comment by raiguard** [comment]
`event_handler` is a wrapper over `script.on_event`. `script.on_event` only supports one handler per event, so `event_library` exists to allow multiple handlers to exist. It just calls `script.on_event` and gives it a function that loops over all the functions you specified and calls them.
