### ISSUE TITLE
doesn't load with the following mods

### ISSUE THREAD

**Issue by blackskycrusader** [raiguard/EditorExtensions#148]
### Description

The testing scenario provided by this mod wont load with the mods that I'm currently using:

[mod-list.zip](https://github.com/raiguard/EditorExtensions/files/12700249/mod-list.zip)

### Reproduction

1. Load the mods provided (The game is at 1.1.91 and the mods used are up to their current date)
2. Load testing scenario
3. The scenario won't load, thus I have to forcefully close the game.

**Comment by raiguard** [comment]
It loads just fine for me, but takes a while due to all of the mod scripts. I imagine that if you just kept waiting it would eventually load.

**Comment by raiguard** [comment]
Let me know if you encounter this again.
