### ISSUE TITLE
Can't design spaceships in testing lab

### ISSUE THREAD

**Issue by npuldon** [raiguard/EditorExtensions#152]
### Description

[link1](https://cdn.discordapp.com/attachments/737396590960181298/1162077131082317924/image.png?ex=653a9faa&is=65282aaa&hm=e91bac4028f63315c5e3b6d6bce236cbbb1c9b78b61c7fa6999f5c541f2c0ef5&)

[link2](https://cdn.discordapp.com/attachments/1080248010199543870/1162074504848216084/image.png?ex=653a9d38&is=65282838&hm=4c6181c744334d5ec2cd6f067e7360db8dfd73e69cdc465a18727c84014c0830&)

### Reproduction

Go into testing lab, try to place spaceship console on spaceship flooring

**Comment by raiguard** [comment]
As per discussion with Wiwiweb on discord, this isn't currently possible without enormous hacks and I do not want to implement enormous hacks.
