### ISSUE TITLE
inventory cut off

### ISSUE THREAD

**Issue by kuxynator** [raiguard/EditorExtensions#153]
### Description

After closing the editor, the inventory is trimmed and I loose all items  and filter above 160 slots.

the strange thing is that so far there have been no problems with it. i have already loaded an older savegame and synced the mods and settings. but it doesn't help. as soon as i use the editor now,. the inventory is cut off.

I can't say exactly what I did before that caused this. especially after loading a savegame, with the same mod versions, the problem shouldn't happen anymore.

If I start a new game the problem remains.

Any idea how to fix this?

**Comment by raiguard** [comment]
The "inventory sync" feature will clamp the inventory to the smaller of your editor or character inventories. To avoid losing items, turn off inventory sync or set your character's inventory to be the same size as the editor inventory.
