### ISSUE TITLE
cargo_wagon is nil

### ISSUE THREAD

**Issue by kuxynator** [raiguard/EditorExtensions#154]
### Description

![image](https://github.com/raiguard/EditorExtensions/assets/66268429/811903a9-7c5b-4404-b2bf-dee4d8cf25f3)

could you check if cargo_wagon is available and activate the features only if it present

**Comment by USSX-Hares** [comment]
@kuxynator can you add more details on how to reproduce the issue?

**Comment by raiguard** [comment]
Yes, please give more exact reproduction steps. Something deleted the vanilla cargo wagon, which shouldn't really ever happen.
