### ISSUE TITLE
Editor Extensions group don't show in GUI 

### ISSUE THREAD

**Issue by 0rg4sm0tr0n** [raiguard/EditorExtensions#155]
### Description

EE group disappears from crafting panel when space exploration mod is active.
![image](https://github.com/raiguard/EditorExtensions/assets/150630751/10494ec5-d72f-4529-966a-b7eee0205f39)

Also all aggregate passive provider chests that i spawned recently don't contain EE items
![22235](https://github.com/raiguard/EditorExtensions/assets/150630751/16453cb9-74f0-4955-a9b2-9bb22ea24bf3)

All mentioned problems seems true only when space exploration is enabled.

Factorio and mods versions are latest.

**Comment by USSX-Hares** [comment]
@0rg4sm0tr0n have you cheat mode enabled?

**Comment by 0rg4sm0tr0n** [comment]
@USSX-Hares Yes, it is enabled in that save. Only solution i found is just creating a new sandbox world

**Comment by raiguard** [comment]
I am unable to reproduce, can you please attach your save file?

**Comment by peter-bozovic** [comment]
I'm encountering the similar issue after enabling some additionnal mods for my game !

Main issue is the missing "testing tools" tab in the crafting menu ...

Attached savefile: [Broken EE.zip](https://github.com/raiguard/EditorExtensions/files/15286408/Broken.EE.zip)

Thanks :)
