### ISSUE TITLE
No UI for Infinity Pipe and Infinity Accumulator

### ISSUE THREAD

**Issue by alanmccallum** [raiguard/EditorExtensions#157]
### Description

[factorio-current.log](https://github.com/raiguard/EditorExtensions/files/13444854/factorio-current.log)
Clicking on the infinity pipe and accumulator triggers the "ui open" sound but nothing appears on screen. Pressing E or clicking anywhere on the screen triggers the "ui close" sound.
I have tried this on the Editor Extensions/Testing scenario, and the Sandbox scenario.
Possibly unrelated but when opening /editor there are 8 Infinity Pipes and 7 Infinity Accumulators.

Other infinity devices work correctly. After removing the mod, the base equivalents work correctly.

**Comment by USSX-Hares** [comment]
@alanmccallum can you share the entire mods list you are using?

**Comment by alanmccallum** [comment]
I removed all but factorio base and editor extensions and started a new map
to rule out conflicts.

**Comment by raiguard** [comment]
Did you accidentally enable the `hide-mod-guis` debug setting? Press `F4`, then `Control+F` and search for it in that menu.

**Comment by alanmccallum** [comment]
That was it, not sure how/when I did that...
