### ISSUE TITLE
Enable circuit network for infinity cargo wagon and Infinity fluid wagon

### ISSUE THREAD

**Issue by CanadianBeaver** [raiguard/EditorExtensions#160]
Please add feature for setup up the circuit conditions with possibility to set the infinity filters based on circuit network comes from train station.

**Comment by CanadianBeaver** [comment]
![image](https://github.com/raiguard/EditorExtensions/assets/20358069/9c623bee-f1a1-4073-9f81-4f79773cc0df)

**Comment by raiguard** [comment]
This isn't very feasible whatsoever without murdering UPS. I'm sorry!
