### ISSUE TITLE
Editor Extension mode just shows blackness

### ISSUE THREAD

**Issue by ajklotz** [raiguard/EditorExtensions#161]
### Description

If I press the Fill with lab tiles, it just generates earth like surface.

![image](https://github.com/raiguard/EditorExtensions/assets/9448682/65d8890b-b131-4ec1-b3e4-564fcf278bb8)

**Comment by raiguard** [comment]
Some mod has changed the lab tile graphics. "Fill with lab tiles" is a base game feature, so it has nothing to do with EE.
