### ISSUE TITLE
[Question] Can you keep Editor Extensions enabled for regular playthroughs?

### ISSUE THREAD

**Issue by Nevrai** [raiguard/EditorExtensions#162]
### Description

Hi, I was wondering if having Editor Extensions installed, without disabling it, whilst playing regular games, on an existing modded save would cause any issues. Is it fine to keep it enabled? Will it cause any conflicts, add any visible items or recipes, or run any commands?

**Edit**: I do see that having this mod installed adds a button to enable the map editor, which I would prefer not having. Is there a way to disable this – not just hiding it in the shortcut bar?

**Comment by raiguard** [comment]
Removing the shortcut button would require a game restart. You can keep EE enabled during regular games just fine, if you don't want to use it then just don't use it.
