### ISSUE TITLE
Constant Resource explosions when switching

### ISSUE THREAD

**Issue by MadManStanley** [raiguard/EditorExtensions#163]
### Description

Been having issues when i try to swap from my regular SE game to the Editor layer to tweak some blueprints quick, only for it to cause a massive performance and frame drop as the game .
![20240204215235_1](https://github.com/raiguard/EditorExtensions/assets/158982038/293d1ee1-eb07-4da0-abca-015f15e1506c)
Attached a screenshot of what was happening, i had to switch it off because it was tanking my save, it showed no signs of ending it anytime soon
Relatively new to the mod, really enjoying it, but issues like this make it useless for the time being at least for me.

**Comment by raiguard** [comment]
Do you use Ultimate Research Queue? I encountered this a while back and it was actually that mod's fault.
