### ISSUE TITLE
No access to Editor Extension (2.2.4)

### ISSUE THREAD

**Issue by Hammer4th** [raiguard/EditorExtensions#165]
### Description

I just updated the Editor Extension and now I have no more access to my files that I was working on and receive the following:

The mod Editor Extensions (2.2.4) caused a non-recoverable error.

Error while running event EditorExtensions::on_player_toggled_map_editor (ID 123)
__EditorExtensions__/scripts/inventory-filters.lua:230: attempt to index field 'applied_default_filters' (a nil value)
stack traceback:
	__EditorExtensions__/scripts/inventory-filters.lua:230: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>

### Reproduction

1. Selecting Map Editor
2. Selecting Edit scenario
3. Selecting my file name such as testing then play
4. received two windows, the first one indicates the following: removed entities  ee-infinity-loader-inserter (inserter) 138; ee-infinity-loader-loader (loader-1x1) 35; ee-infinity-loader-loader-express (loader-1x1) 26; ee-infinity-loader-loader-fast (loader-1x1) 8 and Changed entities: ee-infinity-loader-logic-combinator->ee-infinity-loader-dummy-combinator 69  Then I select Confirm.  The second window is the bug report indicated in the description box above. 
5. After selecting the confirm button I am send back to the Main menu option of factorio

**Comment by raiguard** [comment]
Don't use the `Map editor` option on the main menu, it causes issues with mods such as this. I recommend downgrading EE, saving the scenario as a map, moving it to your saves folder, and using it from there. You can toggle the map editor in a regular game with Control+Alt+E.
