### ISSUE TITLE
Infinity Loader Bug with Deadlock Compact Loaders

### ISSUE THREAD

**Issue by sassxolotl** [raiguard/EditorExtensions#166]
### Description

[factorio-current.log](https://github.com/raiguard/EditorExtensions/files/14341992/factorio-current.log)

placing an infinity loader after a compact loader from Deadlock's mod deletes the infinity loader if the compact loader is feeding towards it. 

https://github.com/raiguard/EditorExtensions/assets/160119232/54fbd2af-9729-4dc4-a27a-c7f964631aaa

video attached shows behavior and number of loaders in hand decreasing along with the sound and animation of an entity being placed, but loader enters it's own infinite dimension by being loaded into itself. Conclusion that Deadlock loaders too powerful, pls nerf. 

### Reproduction

load save, place compact loader in default configuration, place infinity loader to accept output from compact loader. 

This is a brand new editor world that I just loaded into with the mods shown in the log.

**Comment by raiguard** [comment]
Deadlock's stacking beltboxes is deleting the infinity loader's internal infinity chest. Please report this to that mod's author.
