### ISSUE TITLE
[SE compatibility] Resources are spawned on start of the Editor Ext. scenario when SE is active

### ISSUE THREAD

**Issue by USSX-Hares** [raiguard/EditorExtensions#167]
### Description

See screenshot attached.

### Reproduction

1. Install SE & EE
2. Start EE-specific scenario

### Result
* SE-specific starting patches are spawned
* SE core dredging points are spawned
![image](https://github.com/raiguard/EditorExtensions/assets/29100587/10220ba7-6a66-483b-83a3-33b6afbf483b)

Also, other SE-specific events like meteors are spawned too

**Comment by raiguard** [comment]
I'm pretty sure this has been fixed in the interim. I will test again once SE 0.7 is out.
