### ISSUE TITLE
[Feature Request] Use upgrade planner to switch between infinite wagons/chests to regular ones

### ISSUE THREAD

**Issue by dv-morais** [raiguard/EditorExtensions#169]
### Description

Hello,

Usually, after I finish creating my city block blueprint I like to do a rundown on it to see how things are behaving so I set up some infinite wagons to supply the block.

after performing the test I need to delete all the infinite wagons to replace then with the regular ones. This is a boring activity when you have wagons to replace and you can forget to change some.

Is it possible to add the infinite entities to the upgrade planner as upgrade of their regular counterparts? it would make replacing things after testing so much easier and less error prone.

thanks in advance

**Comment by raiguard** [comment]
I don't want to do this because I don't want players to accidentally order this construction in a regular game.

There are probably mods out there that can do this.
