### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by KX5-jeron** [raiguard/EditorExtensions#173]
### Description

Not a bug really, but is there a way to allow friends playing in your hosted world access to the testing world?? they have the button but says they don't have permission to use the map editor

**Comment by raiguard** [comment]
You will need to promote your friends to administrators; only administrators can use the map editor.

If you do not want to use this, I can recommend [Blueprint Sandboxes](https://mods.factorio.com/mod/blueprint-sandboxes?from=search) as an alternative to EE.
