### ISSUE TITLE
[Suggestion] Liquid tank in Editor Extension mod

### ISSUE THREAD

**Issue by Gamer88150** [raiguard/EditorExtensions#174]
### Description

Good morning, 
Is it possible to add infinite liquid tanks to the mod?
And make sure that it also supports liquids from other mods (I'm thinking following the Bon's and Angel's mods)
Kind regards

**Comment by raiguard** [comment]
You can simply connect an infinity pipe to a storage tank. In 2.0 the infinity pipe's filter will apply to the whole segment instantly.
