### ISSUE TITLE
Testing prod module doesn't work for finished products

### ISSUE THREAD

**Issue by dnemes** [raiguard/EditorExtensions#175]
### Description

The testing (deep red) prod mod's description says that it works for finished products as well not just intermediates, but in reality it can't be added to assemblers since the 2.0 update. 

### Reproduction

In editor mode, try and add a super prod mod to any buildings with a finished recipe set.

**Comment by raiguard** [comment]
This is actually unfixable. Starting in 2.0, recipes put a blanket ban on certain module effects that cannot be overwritten by specific modules. I will update the description.
