### ISSUE TITLE
Leaving the editor while in remote view causes all entities in your factory to turn into enemy entities

### ISSUE THREAD

**Issue by TheGarbanzo** [raiguard/EditorExtensions#176]
### Description

Leaving the editor while in remote view (while in the editor) causes entire factory to become hostile structures 

### Reproduction

1. Enter editor surface
2. Open remote view
3. Leave editor via hotkey

**Comment by blackheart3d** [comment]
+1

**Comment by blackheart3d** [comment]
To re-emphasise on what @TheGarbanzo said, if you don't close the remote view before exiting the editor it does this. The only way to fix is to roll back your save as far as I can tell

**Comment by TheGarbanzo** [comment]
> To re-emphasise on what @TheGarbanzo said, if you don't close the remote view before exiting the editor it does this. The only way to fix is to roll back your save as far as I can tell

There actually was another way to fix. Youd have to bring up the editor while in your factory and use it to make all your entities neutral. It's for sure not ideal but could save you if you spent a lot of time in the editor and didn't noticed that you've triggered the bug

**Comment by Krealle** [comment]
Just encountered this bug myself, it also seems to reset all your infinite research.

**Comment by raiguard** [comment]
Thanks for the report. Fixing this properly will require a mod API addition, so it will be a little bit.

**Comment by scponder504** [comment]
I found that using the command 
`/c game.players["YourUsername"].force = "player"`
fixes it. As the factory stays the same, and the player is the one who changes forces.
