### ISSUE TITLE
Editor Extensions leaves behind `EE_TESTSURFACE_1` under Remote View->Surfaces even after removing the mod

### ISSUE THREAD

**Issue by epylar** [raiguard/EditorExtensions#182]
### Description

Editor Extensions leaves behind `EE_TESTSURFACE_1` under Remote View->Surfaces even after removing the mod.

Would be nice to have a cleanup button as a workaround, which could be done by the player prior to uninstalling the mod.

### Reproduction

1. Make new game with Base mod, Elevated Rails, Quality, Space Age, Editor Extensions 2.3.0, and Factorio Library 0.15.0. Factorio version: 2.0.11. Set "Testing lab" to "Personal". Save and reload with new settings.
2. Control-Alt-E to enter the test lab
3. Control-Alt-E to leave the test lab
4. Save game
5. Disable Editor Extensions and Factorio Library mods
6. Reload game
7. Observe `EE_TESTSURFACE_1` still listed in remote view (attached save file)

[editor-extensions-issue-003.zip](https://github.com/user-attachments/files/17534681/editor-extensions-issue-003.zip)

**Comment by arileybuhrow** [comment]
Confirmed; ran into this same issue, uninstalled hoping for it to disappear, no change.
