### ISSUE TITLE
Update Editor Extensions/Testing scenario so that there are no migrations

### ISSUE THREAD

**Issue by Atria1234** [raiguard/EditorExtensions#190]
### Description

When new scenario is started it shows migration content

![obrazek](https://github.com/user-attachments/assets/3ba68ea5-cb26-4ba3-bfe0-89786b234e2a)

### Reproduction

1. Start new game
2. Select Editor Extensions/Testing scenario

**Comment by raiguard** [comment]
The testing scenario is created on the vanilla game, without space age. These are changes that space age introduces over vanilla.
