### ISSUE TITLE
How do I re-enable the Testing Tools inventory tab?

### ISSUE THREAD

**Issue by UntouchedWagons** [raiguard/EditorExtensions#194]
### Description

The tab disappeared in my last test world so I created a new world using the provided scenario only for the inventory tab to disappear again!

### Reproduction

I don't know how to reproduce this.

**Comment by mkostechuk** [comment]
Try to disable all mods except this one and start a new game. It is possible that some other mod interferes

**Comment by raiguard** [comment]
Yeah, the tab should never disappear, please upload your save file.

**Comment by UntouchedWagons** [comment]
If it happens again in my testing world I'll upload the save file.

**Comment by UntouchedWagons** [comment]
[Testing.zip](https://github.com/user-attachments/files/18044167/Testing.zip)

Okay I managed to get the tab to disable by disabling a mod that adds items (I disabled the Explosive Termites mod)

**Comment by raiguard** [comment]
Thanks for the report, and sorry for the delay. Apparently the game now automatically calls `reset_technology_effects()` when configuration changes, requiring me to unlock all of the testing recipes again. Fixed for the next version.
