### ISSUE TITLE
Super force build over infinity loader deletes loader and renders the tile unusable on space platform

### ISSUE THREAD

**Issue by kingarthur91** [raiguard/EditorExtensions#197]
### Description

if you have a character on the platform and attempt to super force build over an infinity loader the loader gets removed while leaving an invisible collision that claims a loader is still in the tile and wont allow anything else to be placed there. its an edge case of having used the editor while trying to build things

### Reproduction

place an infinity loader on a space platform and attempt to use super force build over it with the player character on the platform via editor teleporting.

**Comment by raiguard** [comment]
This was fixed by #196
