### ISSUE TITLE
Spoiled pentapod eggs in Personal Testing Lab's inventory will spawn at engineer's location if not in Personal Testing Lab at the time of spoilage

### ISSUE THREAD

**Issue by apaksl** [raiguard/EditorExtensions#201]
### Description

If I happen to be in the Personal Testing Lab at the time the spoilage timer ticks over on pentapod eggs, then they spawn in the Personal Testing Lab, but if I'm in the "real world" they spawn at the engineer's location, even if I'm using remote view to look elsewhere.

Editor Extensions version 2.3.1, Factorio version 2.0.20

### Reproduction

1. enable Personal Testing Lab in the mod settings
2. in the Personal Testing Lab environment, create a logistics request for 1 or more Pentapod Eggs
3. exit the Personal Testing Lab
4. wait 20 minutes for the spoilage timer to expire

**Comment by raiguard** [comment]
This is a Factorio issue that I can't really do anything about. The items still exist in the editor inventory and they will eventually spoil. I cannot stop the spoiling process.
