### ISSUE TITLE
"Snap infinity pipe filter to adjacent crafter input" setting doesn't work

### ISSUE THREAD

**Issue by jigsaw3xD** [raiguard/EditorExtensions#207]
### Description

This is on EE 2.3.1 but it wasn't working for me since Factorio updated to 2.0 (and not just in pY)

https://github.com/user-attachments/assets/b0548278-78b9-4e68-9081-3a2f10169cb1

**Comment by raiguard** [comment]
The actual bug here is that the setting still exists.

As of 2.0, you can shift+rightclick the assembler and shift+leftclick the pipe and it will set its filter.
