### ISSUE TITLE
Fail to load mod in vanilla game (no space age)

### ISSUE THREAD

**Issue by 0motta0** [raiguard/EditorExtensions#208]
### Description

The mod EditorExtensions (2.4.0) fails to load on vanilla game (no space age DLC).

### Reproduction

1. Factorio base game, no space age DLC.
2. Update mod to 2.4.0 and confirm changes.
3. "Failed to load mod..." error
4. ![image](https://github.com/user-attachments/assets/a365abfb-90a0-4b66-95fc-2366682fc130)

**Comment by chindraba-work** [comment]
Same error when loading into the expansion binary with Space Age mod turned off and rails on.
Rolling back to 2.3.1 works.
