### ISSUE TITLE
Infinity pipe doesn't show picked liquid when placed as a ghost on the game's surface

### ISSUE THREAD

**Issue by jigsaw3xD** [raiguard/EditorExtensions#217]
### Description

In the blueprint sandbox mod both infinity loader and infinity pipe show their filters

![3mOtDSGhem](https://github.com/user-attachments/assets/c514abfe-2f0b-4f91-8dc2-fb678a9647b7)

But when you've done building your build and paste your BP into the game's surface pipe's chosen liquid doesn't show in the filter anymore which is not ideal cos those filters serve as indicators of which belt/pipe from the bus you need to replace the infinity ghost with.

![LKrev7eUXw](https://github.com/user-attachments/assets/c37e3ded-3cad-48d7-97a2-959d15a33b9c) 
![wrLSyqsC8g](https://github.com/user-attachments/assets/3acad65e-4a8e-446d-8edc-c0d2e909b29f)

P.S. Also i just noticed that the infinity loader has red underground belt despite being hooked to a yellow one. Iirc in 1.1's version of the mod it changed its color and speed based on the belt it's connected to.

**Comment by raiguard** [comment]
The alt mode icon thing is a Factorio bug - please report it on the Factorio forums.

As for the belt speed, I removed that in 2.0 of the mod. It always runs at the fastest speed of all belts currently in the game. Changing the speed depending on what it was connected to was far too complex.
