### ISSUE TITLE
Mod Load Error on Launch

### ISSUE THREAD

**Issue by JPlen** [raiguard/EditorExtensions#96]
Upon attempting to load the game I receive this error message. There is no save file to upload as this occurs at the intial game launch.

Failed to load mods: _ _EditorExtensions_ _/prototypes/entity.lua510: attempt to index field '?' (a nil value)
stack traceback:
_ _EditorExtensions_ _/prototypes/entity.lua510: in main chunk
[C]: in function 'require'
_ _EditorExtensions_ _/data.lua:3: in main chunk

Mods to be disabled:
     EditorExtensions (1.12.10)

My username is Jackna2 or Valkerie (I don't know which to use for this) on Steam as I'm using the steam version of the game (if that is relevant)

[factorio-current.log](https://github.com/raiguard/Factorio-EditorExtensions/files/8505188/factorio-current.log)

Game Build is 1.1.57 (build 59622, win 64)

**Comment by raiguard** [comment]
Please disable EE, and upload a save file with all of the other mods still enabled.

**Comment by raiguard** [comment]
Please upload the save file to a file sharing service, then reach out on the [mailing list](https://lists.sr.ht/~raiguard/factorio-mods-discuss).
