### ISSUE TITLE
Bots disappear when entering lab

### ISSUE THREAD

**Issue by Yelnats321** [raiguard/EditorExtensions#99]
### Description

EditorExtensions 1.13.7, if a bot is going to dock onto your personal roboport, and you enter the lab, the bot appears in the lab.

### Reproduction

1. Have a bot return after constructing an item.
2. Enter the lab while the bot is in orbit, with item sync off.
3. The bot will appear in the lab inventory and disappear from the real world.

**Comment by ajklotz** [comment]
Thanks for filing this, I had this same issue
